import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import { Priority } from 'src/common/enums/priority.enum';

class InitialMessageDto {
  @ApiProperty({ example: 'Customer requested urgent update on shipment status.' })
  @IsString()
  @MaxLength(5000)
  content!: string;

  @ApiPropertyOptional({ example: null })
  @IsOptional()
  @IsString()
  attachmentUrl?: string;
}

export class CreateTicketDto {
  @ApiProperty()
  @IsUUID()
  issueId!: string;

  @ApiProperty()
  @IsUUID()
  customerId!: string;

  @ApiProperty({ example: 'Delayed order delivery in Surulere' })
  @IsString()
  @MaxLength(180)
  title!: string;

  @ApiProperty({ example: 'Delivery' })
  @IsString()
  @MaxLength(120)
  category!: string;

  @ApiProperty({ enum: Priority })
  @IsEnum(Priority)
  priority!: Priority;

  @ApiPropertyOptional({ example: 'Draft summary generated by AI...' })
  @IsOptional()
  @IsString()
  aiDraftSummary?: string;

  @ApiPropertyOptional({ example: 'Sentiment trending from frustrated to neutral...' })
  @IsOptional()
  @IsString()
  aiInsightSummary?: string;

  @ApiPropertyOptional({ type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  internalNotes?: string[];

  @ApiPropertyOptional({ description: 'Optional agent assignment at creation' })
  @IsOptional()
  @IsUUID()
  assignedAgentId?: string;

  @ApiPropertyOptional({ type: [InitialMessageDto] })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => InitialMessageDto)
  initialMessages?: InitialMessageDto[];
}

export type CreateTicketInitialMessage = {
  content: string;
  attachmentUrl?: string;
};